set -g default-terminal "screen-256color"
set -ga terminal-overrides ',xterm-256color:Tc'

# evil
set -g mouse on

set -gq allow-passthrough on
set -g visual-activity off

set -g base-index 1
set -sg escape-time 0

set-option -g status-position top
set -g status-right '#[fg=color249]#(date +"%I:%M%p %m-%d-%Y")#[default]'

# colors
set-option -g status-bg color233
set-option -g status-fg color249
set -g mode-style "fg=color0,bg=color11"
set -g pane-active-border-style 'fg=color238'
set -g pane-border-style 'fg=color236'


