# Some default env vars.
env = HYRCURSOR_THEME,catppuccin-macchiato-dark-cursors
env = HYPRCURSOR_SIZE,24
env = XCURSOR_SIZE,24
#blurls = rofi
#

env = CLUTTER_BACKEND,wayland
env = GDK_BACKEND,wayland,x11
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

#firefox
env = MOZ_ENABLE_WAYLAND,1

#nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# nvidia firefox (for hardware acceleration on FF)?
# check this post https://github.com/elFarto/nvidia-vaapi-driver#configuration
#env = MOZ_DISABLE_RDD_SANDBOX,1
#env = NVD_BACKEND,direct
#env = EGL_PLATFORM,wayland
