# Hyprpaper Configuration File

preload = /home/crab/Pictures/wallpapers/pixel-mario.png
#preload = /home/crab/Pictures/wallpapers/beyond_the_clouds_v01.png
#preload = /home/crab/Pictures/wallpapers/cranes.png
wallpaper = DP-1,/home/crab/Pictures/wallpapers/pixel-mario.png
wallpaper = DP-2,/home/crab/Pictures/wallpapers/pixel-mario.png
wallpaper = DP-3,/home/crab/Pictures/wallpapers/pixel-mario.png
